---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: aakashdevops/3-tier-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

          # REQUIRED FOR HPA
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "300m"
              memory: "128Mi"

          env:
            - name: BACKEND_URL
              value: "http://backend.default.svc.cluster.local:5000"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: LoadBalancer   # MetalLB will assign External IP
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80